version: "2.29.7"

services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=stationSki
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: fares258/tp-ski:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "myuser",
        "spring.datasource.password" : "mypassword",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql": "true"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
