global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_container:3306']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins_container:8082']
